apiVersion: v1
kind: PersistentVolume
metadata:
  name: dnf-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /dnfpv
  storageClassName: dnf-pv
  nodeAffinity: # 这里设置节点亲和
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 192.168.3.14 # 这里我们指定节点，该节点有path路径  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnf
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: dnf-pv

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dnf
data:
  dnf_public_ip: 192.168.3.14

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: dnf
data:
  #Testing1  数据库game密码
  # mysql_db_game_password: VGVzdGluZzE=
  mysql_root_password: SWx3cGJiMSMxJA==
  #gmuser
  gm_account: Z211c2Vy
  # gm_account: Z21fdXNlcg==   #修改
  # gm_account: c3VuZXJweQ==   #修改
  # gm_password: SWx3cGJiMSMx   #修改  testing123
  gm_password: dGVzdGluZzEyMw==
  gm_connect_key: NzYzV1hSQlczUEZUQzNJWFBGV0g=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnf
  template:
    metadata:
      labels:
        app: dnf
    spec:
      restartPolicy: Always
      nodeName: 192.168.3.14
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: dnf
        persistentVolumeClaim:
          claimName: dnf
      - name: memory
        emptyDir:
          medium: Memory
          sizeLimit: 8Gi

      initContainers:
      - name: init-data
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: DNF_DB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql_root_password
              name: dnf
        # - name: DNF_DB_GAME_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       key: mysql_db_game_password
        #       name: dnf  
        image: dnf:centos7net
        imagePullPolicy: IfNotPresent
        # securityContext:
        #   privileged: true
        command: ["/bin/bash"]
        args: ["/home/template/init.sh"]
        volumeMounts:
        - mountPath: /data
          name: dnf
          subPath: data
        - mountPath: /opt/lampp/var/mysql
          name: dnf
          subPath: mysql
      containers:
      - name: dnf
        imagePullPolicy: IfNotPresent
        image: dnf:centos7net
        securityContext:
            privileged: true
        # command: ["/bin/bash", "/data/run.sh"]
        # args: ["/data/run.sh"]
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: PUBLIC_IP
          valueFrom:
            configMapKeyRef:
              key: dnf_public_ip
              name: dnf
        volumeMounts:
        - mountPath: /data
          name: dnf
          subPath: data
        - mountPath: /opt/lampp/var/mysql
          name: dnf
          subPath: mysql
        - mountPath: /home/neople/game/log
          name: dnf
          subPath: log
        - mountPath: /dev/shm
          name: memory